@startuml
!theme amiga 

skinparam linetype ortho

entity "Universidade" as uni {
        ** *uni_id : number <<generated>> **
        --
	*nome : text
}

entity "Sala" as sala {
        ** *sala_id : number <<generated>> **
        --
        capacidade : number
        numero : number
}

entity "Prédio" as predio {
        ** *predio_id : number <<generated>> **
        --
}

entity "Departamento" as dep {
        ** *dep_id : number <<generated>> **
        --
	*nome : text
	orcamento : number
}

entity "Curso" as curso {
        ** *curso_id : number <<generated>> **
        --
	*titulo : text
	creditos : number
}

entity "Instrutor" as instrutor {
        ** *instrutor_id : number <<generated>> **
        --
	*nome : text
	salario : number
}

entity "Seção" as secao {
        ** *secao_id : number <<generated>> **
        --
        *nome : text
	ano : number
}

entity "Ministração" as minis {
        ** *minis_id : number <<generated>> **
        --
}

entity "Aluno" as aluno {
        ** *aluno_id : number <<generated>> **
        --
        *nome : text
	credito : number
}

entity "Período" as periodo {
	** *periodo_id : number <<generated>> **
	--
	dia : text
	hora_inicial : number
	hora_final : number
}

entity "Disciplina" as disc {
	** *disc_id : number <<generated>> **
	--
}

entity "Atividade" as atv {
	** *atv_id : number <<generated>> **
	--
	ano : number
	notas : text
}

entity "Mentorando" as ment {
	** *ment_id : number <<generated>> **
	--
}

uni ||--o{ predio
uni ||--o{ sala
uni ||--o{ aluno
uni ||..o{ instrutor
predio ||--o{ sala
predio ||--o{ dep
predio ||--o{ secao
dep ||--|| curso
dep ||--o{ instrutor
curso ||--|{ secao
curso ||--o{ minis
sala ||--o{ secao
periodo ||--|{ secao
secao ||--|{ minis
minis }|--|| instrutor
instrutor ||--o{ ment
aluno }|--|| dep
aluno ||--o{ atv
aluno ||--o{ ment
secao ||--o{ atv
curso ||--o{ disc
disc -- disc : pre-requesito 
@enduml
