@startuml
!theme amiga 

entity "Universidade" as uni {
        ** *uni_id : number <<generated>> **
        --
        *name : text
}

entity "Sala" as sala {
        ** *sala_id : number <<generated>> **
        --
        *name : text
}

entity "Prédio" as predio {
        ** *predio_id : number <<generated>> **
        --
        *name : text
}

entity "Departamento" as dep {
        ** *dep_id : number <<generated>> **
        --
        *name : text
}

entity "Curso" as curso {
        ** *curso_id : number <<generated>> **
        --
        *name : text
}

entity "Instrutor" as instrutor {
        ** *instrutor_id : number <<generated>> **
        --
        *name : text
}

entity "Seção" as secao {
        ** *secao_id : number <<generated>> **
        --
        *name : text
}

entity "Ministração" as minis {
        ** *minis_id : number <<generated>> **
        --
        *name : text
}

entity "Aluno" as aluno {
        ** *aluno_id : number <<generated>> **
        --
        *name : text
}

uni ||--o{ sala
@enduml
